# Setup
title:            Anthony Burton
tagline:          'Your friendly neighbourhood data scientist'
description:      'Data Science, Machine Learning & Statistics Nerd, Pythonista, Wannabe Jedi'
url:              'https://apburton84.github.io' 
baseurl:          ''

author:
  name:           'Anthony Burton'
  url:            https://apburton84.github.io/ 

# Gemshttp://localhost:4000
plugins:
  - jekyll-paginate
  - jekyll-gist

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://apburton84.github.io/
