# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Anthony Burton
tagline:          'Your friendly neighbourhood data scientist'
description:      'Data Scientist, Machine Learning & Statistics Nerd, Pythonista, Wannabe Jedi'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Anthony Burton'
  url:            https://apburton84.github.io/ 

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://apburton84.github.io/
